# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: technews_api/v1alpha1/search/server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from technews_api.v1alpha1.search.category import services_pb2 as technews__api_dot_v1alpha1_dot_search_dot_category_dot_services__pb2
from technews_api.v1alpha1.search.article import services_pb2 as technews__api_dot_v1alpha1_dot_search_dot_article_dot_services__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='technews_api/v1alpha1/search/server.proto',
  package='technews_api.v1alpha1.search',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)technews_api/v1alpha1/search/server.proto\x12\x1ctechnews_api.v1alpha1.search\x1a\x34technews_api/v1alpha1/search/category/services.proto\x1a\x33technews_api/v1alpha1/search/article/services.proto2\xab\x02\n\rSearchService\x12\x8f\x01\n\x0eListCategories\x12<.technews_api.v1alpha1.search.category.ListCategoriesRequest\x1a=.technews_api.v1alpha1.search.category.ListCategoriesResponse\"\x00\x12\x87\x01\n\x0cListArticles\x12\x39.technews_api.v1alpha1.search.article.ListArticlesRequest\x1a:.technews_api.v1alpha1.search.article.ListArticlesResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[technews__api_dot_v1alpha1_dot_search_dot_category_dot_services__pb2.DESCRIPTOR,technews__api_dot_v1alpha1_dot_search_dot_article_dot_services__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SEARCHSERVICE = _descriptor.ServiceDescriptor(
  name='SearchService',
  full_name='technews_api.v1alpha1.search.SearchService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=183,
  serialized_end=482,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListCategories',
    full_name='technews_api.v1alpha1.search.SearchService.ListCategories',
    index=0,
    containing_service=None,
    input_type=technews__api_dot_v1alpha1_dot_search_dot_category_dot_services__pb2._LISTCATEGORIESREQUEST,
    output_type=technews__api_dot_v1alpha1_dot_search_dot_category_dot_services__pb2._LISTCATEGORIESRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListArticles',
    full_name='technews_api.v1alpha1.search.SearchService.ListArticles',
    index=1,
    containing_service=None,
    input_type=technews__api_dot_v1alpha1_dot_search_dot_article_dot_services__pb2._LISTARTICLESREQUEST,
    output_type=technews__api_dot_v1alpha1_dot_search_dot_article_dot_services__pb2._LISTARTICLESRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEARCHSERVICE)

DESCRIPTOR.services_by_name['SearchService'] = _SEARCHSERVICE

# @@protoc_insertion_point(module_scope)
