# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: technews_api/v1alpha1/search/category/services.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from technews_api.v1alpha1.search.common import metadata_pb2 as technews__api_dot_v1alpha1_dot_search_dot_common_dot_metadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='technews_api/v1alpha1/search/category/services.proto',
  package='technews_api.v1alpha1.search.category',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n4technews_api/v1alpha1/search/category/services.proto\x12%technews_api.v1alpha1.search.category\x1a\x32technews_api/v1alpha1/search/common/metadata.proto\"\'\n\x15ListCategoriesRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\"c\n\x16ListCategoriesResponse\x12I\n\ncategories\x18\x01 \x03(\x0b\x32\x35.technews_api.v1alpha1.search.common.CategoryMetadatab\x06proto3')
  ,
  dependencies=[technews__api_dot_v1alpha1_dot_search_dot_common_dot_metadata__pb2.DESCRIPTOR,])




_LISTCATEGORIESREQUEST = _descriptor.Descriptor(
  name='ListCategoriesRequest',
  full_name='technews_api.v1alpha1.search.category.ListCategoriesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='technews_api.v1alpha1.search.category.ListCategoriesRequest.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=186,
)


_LISTCATEGORIESRESPONSE = _descriptor.Descriptor(
  name='ListCategoriesResponse',
  full_name='technews_api.v1alpha1.search.category.ListCategoriesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='categories', full_name='technews_api.v1alpha1.search.category.ListCategoriesResponse.categories', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=287,
)

_LISTCATEGORIESRESPONSE.fields_by_name['categories'].message_type = technews__api_dot_v1alpha1_dot_search_dot_common_dot_metadata__pb2._CATEGORYMETADATA
DESCRIPTOR.message_types_by_name['ListCategoriesRequest'] = _LISTCATEGORIESREQUEST
DESCRIPTOR.message_types_by_name['ListCategoriesResponse'] = _LISTCATEGORIESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListCategoriesRequest = _reflection.GeneratedProtocolMessageType('ListCategoriesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTCATEGORIESREQUEST,
  '__module__' : 'technews_api.v1alpha1.search.category.services_pb2'
  # @@protoc_insertion_point(class_scope:technews_api.v1alpha1.search.category.ListCategoriesRequest)
  })
_sym_db.RegisterMessage(ListCategoriesRequest)

ListCategoriesResponse = _reflection.GeneratedProtocolMessageType('ListCategoriesResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTCATEGORIESRESPONSE,
  '__module__' : 'technews_api.v1alpha1.search.category.services_pb2'
  # @@protoc_insertion_point(class_scope:technews_api.v1alpha1.search.category.ListCategoriesResponse)
  })
_sym_db.RegisterMessage(ListCategoriesResponse)


# @@protoc_insertion_point(module_scope)
