# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: technews_api/v1alpha1/search/common/metadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='technews_api/v1alpha1/search/common/metadata.proto',
  package='technews_api.v1alpha1.search.common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n2technews_api/v1alpha1/search/common/metadata.proto\x12#technews_api.v1alpha1.search.common\"|\n\x10\x43\x61tegoryMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12M\n\x0esub_categories\x18\x03 \x03(\x0b\x32\x35.technews_api.v1alpha1.search.common.CategoryMetadata\"?\n\x0f\x41rticleMetadata\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x10\n\x08\x63ontents\x18\x03 \x03(\tb\x06proto3')
)




_CATEGORYMETADATA = _descriptor.Descriptor(
  name='CategoryMetadata',
  full_name='technews_api.v1alpha1.search.common.CategoryMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='technews_api.v1alpha1.search.common.CategoryMetadata.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='technews_api.v1alpha1.search.common.CategoryMetadata.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sub_categories', full_name='technews_api.v1alpha1.search.common.CategoryMetadata.sub_categories', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=215,
)


_ARTICLEMETADATA = _descriptor.Descriptor(
  name='ArticleMetadata',
  full_name='technews_api.v1alpha1.search.common.ArticleMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='technews_api.v1alpha1.search.common.ArticleMetadata.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='technews_api.v1alpha1.search.common.ArticleMetadata.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contents', full_name='technews_api.v1alpha1.search.common.ArticleMetadata.contents', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=280,
)

_CATEGORYMETADATA.fields_by_name['sub_categories'].message_type = _CATEGORYMETADATA
DESCRIPTOR.message_types_by_name['CategoryMetadata'] = _CATEGORYMETADATA
DESCRIPTOR.message_types_by_name['ArticleMetadata'] = _ARTICLEMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CategoryMetadata = _reflection.GeneratedProtocolMessageType('CategoryMetadata', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYMETADATA,
  '__module__' : 'technews_api.v1alpha1.search.common.metadata_pb2'
  # @@protoc_insertion_point(class_scope:technews_api.v1alpha1.search.common.CategoryMetadata)
  })
_sym_db.RegisterMessage(CategoryMetadata)

ArticleMetadata = _reflection.GeneratedProtocolMessageType('ArticleMetadata', (_message.Message,), {
  'DESCRIPTOR' : _ARTICLEMETADATA,
  '__module__' : 'technews_api.v1alpha1.search.common.metadata_pb2'
  # @@protoc_insertion_point(class_scope:technews_api.v1alpha1.search.common.ArticleMetadata)
  })
_sym_db.RegisterMessage(ArticleMetadata)


# @@protoc_insertion_point(module_scope)
