# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: technews_api/v1alpha1/search/article/services.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from technews_api.v1alpha1.search.common import metadata_pb2 as technews__api_dot_v1alpha1_dot_search_dot_common_dot_metadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='technews_api/v1alpha1/search/article/services.proto',
  package='technews_api.v1alpha1.search.article',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n3technews_api/v1alpha1/search/article/services.proto\x12$technews_api.v1alpha1.search.article\x1a\x32technews_api/v1alpha1/search/common/metadata.proto\"=\n\x13ListArticlesRequest\x12\x14\n\x0c\x63\x61tegory_url\x18\x01 \x01(\t\x12\x10\n\x08num_page\x18\x02 \x01(\x05\"^\n\x14ListArticlesResponse\x12\x46\n\x08\x61rticles\x18\x01 \x03(\x0b\x32\x34.technews_api.v1alpha1.search.common.ArticleMetadatab\x06proto3')
  ,
  dependencies=[technews__api_dot_v1alpha1_dot_search_dot_common_dot_metadata__pb2.DESCRIPTOR,])




_LISTARTICLESREQUEST = _descriptor.Descriptor(
  name='ListArticlesRequest',
  full_name='technews_api.v1alpha1.search.article.ListArticlesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category_url', full_name='technews_api.v1alpha1.search.article.ListArticlesRequest.category_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_page', full_name='technews_api.v1alpha1.search.article.ListArticlesRequest.num_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=206,
)


_LISTARTICLESRESPONSE = _descriptor.Descriptor(
  name='ListArticlesResponse',
  full_name='technews_api.v1alpha1.search.article.ListArticlesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='articles', full_name='technews_api.v1alpha1.search.article.ListArticlesResponse.articles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=302,
)

_LISTARTICLESRESPONSE.fields_by_name['articles'].message_type = technews__api_dot_v1alpha1_dot_search_dot_common_dot_metadata__pb2._ARTICLEMETADATA
DESCRIPTOR.message_types_by_name['ListArticlesRequest'] = _LISTARTICLESREQUEST
DESCRIPTOR.message_types_by_name['ListArticlesResponse'] = _LISTARTICLESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListArticlesRequest = _reflection.GeneratedProtocolMessageType('ListArticlesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTARTICLESREQUEST,
  '__module__' : 'technews_api.v1alpha1.search.article.services_pb2'
  # @@protoc_insertion_point(class_scope:technews_api.v1alpha1.search.article.ListArticlesRequest)
  })
_sym_db.RegisterMessage(ListArticlesRequest)

ListArticlesResponse = _reflection.GeneratedProtocolMessageType('ListArticlesResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTARTICLESRESPONSE,
  '__module__' : 'technews_api.v1alpha1.search.article.services_pb2'
  # @@protoc_insertion_point(class_scope:technews_api.v1alpha1.search.article.ListArticlesResponse)
  })
_sym_db.RegisterMessage(ListArticlesResponse)


# @@protoc_insertion_point(module_scope)
